Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
# src += Glob('samples/led_sample.c')
# src += Glob('samples/uart_sample.c')
# src += Glob('devices/OLED_zjy/*.c')
# src += Glob('samples/oled_sample.c')

# src += Glob('devices/TM1640/*.c')
# src += Glob('samples/tm1640_sample.c')

# src += Glob('apps/uart1uart2switch/*.c')

src += Glob('devices/TM1640/*.c')
src += Glob('apps/uart2nixietube/*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
